### ISSUE TITLE
Update for alignment with https://github.com/pangeo-forge/pangeo-forge-azure-bakery/pull/27

### ISSUE THREAD

**Issue by sharkinsspatial** [pangeo-forge/pangeo-forge-gcs-bakery#21]
Todo:
- [x] Update deploy target
- [x] Inline loki with deploy
- [x] Seperate cluster connection target
- [x] Change SED rn to En
- [x] Add get grafana admit creds

**Comment by sharkinsspatial** [comment]
@tracetechnical Do you have a branch where you are undertaking this work?

**Comment by tracetechnical** [comment]
TODO:
- [ ] Vanilla test

**Comment by tracetechnical** [comment]
Fixed by #22

**Comment by tracetechnical** [comment]
Closed by #22
