### ISSUE TITLE
Maybe drop `required_providers` from `terraform/providers.tf`

### ISSUE THREAD

**Issue by cisaacstern** [pangeo-forge/pangeo-forge-gcs-bakery#28]
In working on #19, I ran into a problem with running `terraform init` from my Apple Silicon laptop, which appeared to be the same issue described here: https://stackoverflow.com/questions/66281882/how-can-i-get-terraform-init-to-run-on-my-apple-silicon-macbook-pro-for-the-go

The accepted answer to the question is relatively involved, but a secondary answer simply suggests

```diff
# terraform/providers.tf

- terraform {
-  required_providers {
-    google = {
-      source  = "hashicorp/google"
-     version = "3.5.0"
-    }
-  }
- }
provider "google" {
  project = var.project_name
  region  = "us-central1"
  zone    = "us-central1-c"
}
terraform {
  backend "gcs" {
    bucket = "terraform-tfstate-gcp"
    prefix = "terraform/state"
  }
}
```
which worked perfectly for me. @tracetechnical @sharkinsspatial, are there other platforms on which you'd expect `required_providers` to be, no pun intended, required?

**Comment by tracetechnical** [comment]
As far as i know, it is good practise to version lock providers in this way.

See https://www.terraform.io/language/providers/requirements.

I feel that removing this just to fix an issue regarding apple silicon is not the right way forward, as there are other non apple users who may have a sub optimal experience as a result of this change.

**Comment by tracetechnical** [comment]
Closing inline with above comment.
